id: pull_request
learningObjectives:
  - Open a pull request to make a change to the codebase.
hints:
  - Make sure you change the frontend/src/custom.scss file.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "We will make a small change to the style, let's change the font color of sign in and sign up buttons."
          - text:  "So, :instruction[open the `frontend/src/custom.scss` file and add the following line at the end of the file:]"
          - text: |-
                   ```css
                   .navbar-nav .nav-item .nav-link {
                      color: #FFFFFF;
                   } 
                   ```
          - text: Once you're done, :instruction[Commit & Create a pull request] from the source control menu.
          - text: "![](${commit-and-create-pr.png})"
          - text: Add a description to the pull request, with a brief explanation of the change you made, and add a link to the GitHub issue that this PR is related to and hit `Create`.
          - text: "![](${create-pr.png})"
          - text: I'll be here to review it.
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Checking now
            - actionId: github_pr_comment
              params:
                person: lucca
                message: Checking now.
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_does_file_contain
                params:
                  fileName: frontend/src/custom.scss
                  regex: "color: #ffffff"
                  flags: "i"
            then:
              do:
                - actionId: github_pr_approve
                  params:
                    person: lucca
                    message: Looking good! You can merge the PR now.
                - actionId: bot_message
                  params:
                    person: lucca
                    messages:
                      - text: "You've just completed the GitHub Fundamentals quest—great job! Now you understand how to create issues, start discussions, work with branches, and open pull requests."
                      - text: "Next, to collaborate more effectively, it's important to communicate clearly in GitHub. One key way to do that? Mastering Markdown—the formatting language used in issues, pull requests, and README files."
                      - text: "👉 Check out the \"Communicate using Markdown\" module on [Microsoft Learn](https://learn.microsoft.com/en-us/training/modules/communicate-using-markdown/) to level up your writing and make your contributions clearer and more professional."
            else:
              do:
                - actionId: bot_message
                  params:
                    person: lucca
                    messages:
                      - text: Looks like you did not update the `frontend/src/custom.scss` file. Remember to add the
                          relevant content.
                - actionId: github_pr_reject
                  params:
                    person: lucca
                    message: Looks like you did not update the `frontend/src/custom.scss` file. Remember to add the
                      relevant content.
        github_pr_merged:
          do:
            - actionId: finish_step
